/* Generated By:JavaCC: Do not edit this line. MoneyCConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MoneyCConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int VARIAVEL = 12;
  /** RegularExpression Id. */
  int INT = 13;
  /** RegularExpression Id. */
  int STRING = 14;
  /** RegularExpression Id. */
  int IDENTIFICADOR_VARIAVEL = 15;
  /** RegularExpression Id. */
  int FIM_COMANDO = 16;
  /** RegularExpression Id. */
  int TIPO_STRING = 17;
  /** RegularExpression Id. */
  int TIPO_INTEIRO = 18;
  /** RegularExpression Id. */
  int ENTRADA_DADOS = 19;
  /** RegularExpression Id. */
  int REL_MAIOR_IGUAL = 20;
  /** RegularExpression Id. */
  int REL_MENOR_IGUAL = 21;
  /** RegularExpression Id. */
  int REL_MAIOR = 22;
  /** RegularExpression Id. */
  int REL_MENOR = 23;
  /** RegularExpression Id. */
  int REL_IGUALDADE = 24;
  /** RegularExpression Id. */
  int REL_DIFERENCA = 25;
  /** RegularExpression Id. */
  int ATRIBUICAO = 26;
  /** RegularExpression Id. */
  int SAIDA_DADOS = 27;
  /** RegularExpression Id. */
  int POTENCIA = 28;
  /** RegularExpression Id. */
  int MULTIPLICACAO = 29;
  /** RegularExpression Id. */
  int DIVISAO = 30;
  /** RegularExpression Id. */
  int ADICAO = 31;
  /** RegularExpression Id. */
  int SUBTRACAO = 32;
  /** RegularExpression Id. */
  int CONCATENACAO = 33;
  /** RegularExpression Id. */
  int LOGICO_E = 34;
  /** RegularExpression Id. */
  int LOGICO_OU = 35;
  /** RegularExpression Id. */
  int LOGICO_NAO = 36;
  /** RegularExpression Id. */
  int SE = 37;
  /** RegularExpression Id. */
  int SENAO = 38;
  /** RegularExpression Id. */
  int FIM_SE = 39;
  /** RegularExpression Id. */
  int ENQUANTO = 40;
  /** RegularExpression Id. */
  int FIM_ENQUANTO = 41;
  /** RegularExpression Id. */
  int ABRE_EXPRESSAO = 42;
  /** RegularExpression Id. */
  int FECHA_EXPRESSAO = 43;
  /** RegularExpression Id. */
  int ABRE_BLOCO = 44;
  /** RegularExpression Id. */
  int FECHA_BLOCO = 45;
  /** RegularExpression Id. */
  int VIRGULA = 46;
  /** RegularExpression Id. */
  int NOME_FUNCAO = 47;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int comment = 1;
  /** Lexical state. */
  int multilinecomment = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"/*\"",
    "\"//\"",
    "\"\\r\"",
    "\"\\n\"",
    "<token of kind 9>",
    "\"*/\"",
    "<token of kind 11>",
    "<VARIAVEL>",
    "<INT>",
    "<STRING>",
    "\"VAR\"",
    "\";\"",
    "\"string\"",
    "\"int\"",
    "\"leia\"",
    "\">=\"",
    "\"<=\"",
    "\">\"",
    "\"<\"",
    "\"==\"",
    "\"!=\"",
    "\":=\"",
    "\"exibe\"",
    "\"^\"",
    "\"*\"",
    "\"/\"",
    "\"+\"",
    "\"-\"",
    "\".\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "\"SE\"",
    "\"SENAO\"",
    "\"FIM_SE\"",
    "\"ENQUANTO\"",
    "\"FIM_ENQUANTO\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\",\"",
    "<NOME_FUNCAO>",
  };

}
